### PR TITLE
I changed my github username

### PR DESCRIPTION
**Pull request by xvxx**
I'm retiring my old github username and switching to a new one for the new year. 

- the artist formerly known as *dvkt*

### CODE REVIEW

**Comment by Lartu** [comment]
Wonderful, Chris! I'm glad you are using your full name here! Shall I change dvkt to Chris West on the website as well? :smiley_cat: 

Btw what does xvxx stand for?

**Comment by xvxx** [comment]
> Shall I change dvkt to Chris West on the website as well? 😺

Sure!

> Btw what does xvxx stand for?

It's an old childhood nickname - my grandma called me it when I was a baby, and I guess it just stuck!

**Comment by Lartu** [comment]
> It's an old childhood nickname - my grandma called me it when I was a baby, and I guess it just stuck!

Your grandma called you "ex vee ex ex"? 

Now that your username has changed, shall I still contact you to the usual email address?

**Comment by xvxx** [comment]
Well, she pronounced it "Peanut", but she spelled it xvxx. I'm not sure she ever learned to write properly. But anyway, yes, my regular email still works! I might be switching to ProtonMail in the future to de-Google myself further (I use GMAIL), but I will let you know and try to never break the old one.

**Comment by Lartu** [comment]
Hahahaha

Wonderful!

**Pull request merged**
