### PR TITLE
Add Homebrew install to readme

### PR DESCRIPTION
**Pull request by SeekingMeaning**
https://formulae.brew.sh/formula/ldpl

### CODE REVIEW

**Comment by Lartu** [comment]
This is wonderful! Thank you very much for your contribution!

**Comment by Lartu** [comment]
I want to ask you something; starting with LDPL 4.5 (still in development), when you build LDPL using `make` it installs some library files (.cpp) in `/usr/local/lib/ldpl`. Do you know if this could work as well with Homebrew, once we release it?

**Comment by SeekingMeaning** [comment]
I'm not 100% certain but we should be able to get it to work

I might suggest changing this line https://github.com/Lartu/ldpl/blob/master/makefile#L48 to:

```Makefile
LDPLLIBLOCATION = "$(PREFIX)/lib/ldpl"
```

**Comment by Lartu** [comment]
Ah! Yes! There, changed. Thank you very, very much! :smile:

**Pull request merged**
