### PR TITLE
Experimental support for C++ extensions

### PR DESCRIPTION
**Pull request by dvkt**
Hi, my boss is making me rewrite our cryptocurrency platform using LDPL and so I need to be able to write custom subroutines in C++ and access them from my LDPL programs. For performance reasons. 

This branch adds basic C++ extension support to the compiler for mac & linux. It's probably not the way it should be done, but I thought maybe it could start a discussion at least. 

Have you thought about how this should work? I'm sure people want to write games and voting machines and all sorts of things in LDPL. 

"Extensions" according to this branch are `.a` static archives accompanied by an`.h` file that can contain C++ functions and variables which can be called from LDPL as if they were subprocedures and text/number/vector variables.

For example, this LDPL code: 

```cobol
STORE "cool" IN temp
CALL weather
```

Could be calling a C++ function that looks like:

```c++
void SUBPR_WEATHER()
{
    cout << "weather is: " << VAR_TEMP << endl;
}
```

The glue is the extension's `.h` file, which needs to declare which variables and functions it's using:

```c++
extern string VAR_TEMP;
void SUBPR_WEATHER();
```

The `ldpl` compiler will look at the `.h` file to figure out what variables and subprocedures are in the extension's `.a` archive file. It uses that information to let you work with those variables and subprocedures as if they were defined in LDPL code.

Building instructions are in the [README.md](https://github.com/dvkt/ldpl/blob/extensions/examples/cpp-extension/README.md) in [examples/cpp-extension](https://github.com/dvkt/ldpl/blob/extensions/examples/cpp-extension/), but basically you just create an `.o` file for each `.cpp` and `.h` file you have, then pack those into an `.a` file with `ar`:

```
$ c++ -c my-ext.cpp -std=gnu++11 -o my-ext.o
$ ar -cvq my-ext.a my-ext.o
```

To build an LDPL program that uses `my-ext.a`, pass `my-ext.h` to `-i=`:

```
$ ldpl -i=my-ext.h program.ldpl
```

Both `my-ext.h` and `my-ext.a` must be in the same file as `program.ldpl`, and `my-ext.a` must be built for the current architecture.

I have an example extension at https://github.com/dvkt/ldplnoise which wraps linenoise.hpp, allowing for an `ACCEPT` prompt that has some readline features like up/down history. I've only tested it on macos and arch linux so it could be riddled with bugs still.

Anoter simpler example is at https://github.com/dvkt/hi-c 

There's also the simplest example in this branch at [examples/cpp-extension](https://github.com/dvkt/ldpl/blob/extensions/examples/cpp-extension/). It has a `Makefile` which will build a version of `ldpl` specific to this branch to test it. And that README I mentioned.

## Code

Most of the code is in the `ldpl` compiler in the code for handling `-i=` flags. If a `.h` file is passed, `ldpl` will look for a `.a` file and then include that when building the final compiled program. It'll also parse the lines of the `.h` file to figure out what variables and subprocedures are in the extension. 

## Problems

- Mac/Linux only, and I've only tested on Arch Linux and MacOS Mojave. 
- Not sure how you envision the syntax. I just reused what was existing. 
- Requires building `.a` for the extension using `c++` and `ar`. Maybe it could be automated to be easier for extension authors.
- Requires both an `.a` file and a `.h` file to use an extension in LDPL code. 
- Requires parsing a `.h` file in C++, which is gonna be brittle. 
- I'm not sure if you even want LDPL to ever do this kind of stuff! 
- Depends directly on LDPL's internal name wrangling format for variables and subprocedures which makes the var/sub names kinda nasty if you want to use - / . etc. 
- Probably lots of bugs, did I mention that.
- No way to use `ldpl_number` or the vectors without declaring the prototypes yourself, which is what I do in the `hi-c` example. 
- No clue how this will work with dynamic libraries, or if it even can.
- My C++ is bad. 
- …

Anyway curious to hear how/if you think extensions should work in LDPL. And let me know if I left anything out / what I screwed up thanks!

### CODE REVIEW

**Comment by Lartu** [comment]
Woah this looks awesome! I'm quite busy atm and this is something I would love to sit down and discuss more, so I'll leave this hanging here and I will reply in more detail once I have a chance to sit at my computer.

Sorry and thank you!

**Comment by dvkt** [comment]
@lartur Awesome, yeah, take your time! No rush. I mostly just wanted to get something working so I could finish my little Gopher client, [GILD](https://github.com/dvkt/gild). 

I also just added the ability to put `extern void SUBPR_SOMETHING();` in your extension's `.h` file so you can call subprocedures defined in LDPL from C++.

This could be useful for games - maybe there's an SDL extension with a loop that calls your own custom `DRAW` and `UPDATE` subprocedures each iteration. Or you could define LDPL callbacks this way, like `HTTP-SUCCESS` and `HTTP-ERROR` subprocedures for use in an HTTP extension. 

I'll keep this branch updated, but no problem ditching it if there's another better approach :+1:

**Comment by Lartu** [comment]
Well, here I am! I **LOVE** THIS. I love the way you made it work, it's the same I would've done. Let's address all of your issues one by one:

> Mac/Linux only, and I've only tested on Arch Linux and MacOS Mojave. 

I shall test it later on Windows (I'm on Linux ATM) to see how it goes. I think it should work fine the way it is right now.

> Not sure how you envision the syntax. I just reused what was existing. 

This is great! I would just change something. You parse the `.h` file to get all the variables and the function names. I wouldn't do this. I'd just add two new commands to the language `EXTERNAL CALL` or something like that and the option to declare external variables (maybe an `EXTERNAL DATA` section or something on the lines of that). What for? So the `.h` file doesn't have to be checked. You are supposed to write those variables and functions with the right case and be sure they exist. If they don't exist, the C++ compiler will cry when trying to compile the whole thing. It's a little scruffier, but I think that'd be easier for us. That said, I think you wrote the whole .h parser, so if it works fine (I haven't played with it much yet), I'd say let's go with what you've done. I would love to know what do you think about all of this.

> Requires building `.a` for the extension using `c++` and `ar`. Maybe it could be automated to be easier for extension authors.

It could be automated, maybe. But at the moment, that's the way it is and I think that's just fine. It's not hard at all, you summed the whole thing up in just a few sentences on your readme!

> Requires both an `.a` file and a `.h` file to use an extension in LDPL code.

I don't really see this as a problem. That's the way LDPL/C++ extensions are, again!

>  Requires parsing a `.h` file in C++, which is gonna be brittle. 

Same thing as before, we could just not parse `.h` files and that'd be just as fine.

> I'm not sure if you even want LDPL to ever do this kind of stuff!

I've wanted LDPL to do this kind of stuff since day one! Also, you are welcome to add to LDPL whatever you see useful and fit, it's an open, community project. You've even been submiting better contributions than I have!

> Depends directly on LDPL's internal name wrangling format for variables and subprocedures which makes the var/sub names kinda nasty if you want to use - / . etc.

This got me thinking. But I think we could maybe offer extension writers a way to check if a variable exists in an LDPL program or not. Something like `getLDPLTextVariable("variableName");`. Is it possible to do that? Maybe they can declare it as `extern` and use it?
 
> Probably lots of bugs, did I mention that.

Stable LDPL releases are often bug-ridden so... ¯\_(ツ)_/¯ That will be sorted as the feature is used ;)

> No way to use `ldpl_number` or the vectors without declaring the prototypes yourself, which is what I do in the `hi-c` example. 

While that is true, ldpl_numbers are just doubles. I added the `#define` in case we wanted to change the number size, but at the moment that seems unlikely. They could just use double in their code and that'd be alright.

> No clue how this will work with dynamic libraries, or if it even can.

I'll ask some people I know very knowledgeable on the subject and come back with answers. In any case, the `.o` file can be statically linked, or not?, so I don't really see that as a problem.

> My C++ is bad.

I don't see it that way, but in any case mine is worst.

> …

,,,

**Comment by dvkt** [comment]
> Well, here I am! I LOVE THIS. I love the way you made it work, it's the same I would've done.

Great, I'm so happy to hear that! Thank you. 

> I shall test it later on Windows (I'm on Linux ATM) to see how it goes. I think it should work fine the way it is right now.

I'll try and get a Windows VM setup in the next few days so I can test, too. 

> You parse the .h file to get all the variables and the function names. I wouldn't do this.

:+1: I dislike using the `.h` file too, it's brittle and feels wrong. If people use fancy macros it'll surely break, for example. Also I don't think small extensions will even need `.h` files, so it's a bit of hoop jumping.

> I'd just add two new commands to the language EXTERNAL CALL or something like that and the option to declare external variables (maybe an EXTERNAL DATA section or something on the lines of that). 

Okay cool! I like the idea of defining the external interface you expect in LDPL code. One of the other issues with the `.h` file is that subprocedures and variables just magically spring to life in your LDPL code. It would be nice if they were explicit on the LDPL side, for readability and to remove any surprising behavior.

Until the latest release, I was thinking that because there's `CALL SUB-PROCEDURE X` there could be `CALL EXTERNAL X`, but I'm not sure if that's the way you want to take the syntax anymore. So for now, I'll add a new command like this:

     EXTERNAL CALL RL-ACCEPT

And, also for now, I'll add an `IS EXTERNAL` data declaration:

```cobol
DATA:
NAME IS TEXT
RL-ACCEPT IS EXTERNAL TEXT
RL-PROMPT IS EXTERNAL TEXT
```

Does that seem okay or would you rather try to do an `EXTERNAL DATA:` section? Personally I like the idea that `DATA:` is all the data, both internal and external, since it doesn't really matter to your program and you'll probably be using the different variable types alongside one another, but I can make it work if we want to try adding a new section.

> I've wanted LDPL to do this kind of stuff since day one! Also, you are welcome to add to LDPL whatever you see useful and fit, it's an open, community project. You've even been submiting better contributions than I have!

hah, thank you! I'm enjoying watching your vision play out. 

>  They could just use double in their code and that'd be alright.
> ...
> But I think we could maybe offer extension writers a way to check if a variable exists in an LDPL program or not. 

One idea I had was to rename `ldpl.h` to something like `ldpl_compiler.h` and then create a little `lpdl.h` file that extensions and LDPL itself could both use. All the types could be defined in there, as well as a few helper functions/macros to make writing an extension easier. 

I'll experiment with that and see if I can get something like `getLDPLTextVariable("variableName");` working.

I'll update this branch when I make some of these changes, notably removing the `.h` file and the parsing :+1:

**Comment by Lartu** [comment]
I agree with everything you've said so far. I also agree with the fact that `CALL EXTERNAL X` is more reasonable and consistent with our current syntax than `EXTERNAL CALL`, so I'd go with that.

I'll await your updates! Work as you see fit, if you want to introduce a new statement or something, just do it and we can discuss it later if something doesn't work out alright ;D

**Comment by dvkt** [comment]
Okay, made some progress. Loading the actual extension into LDPL is way better now. The compiler code is a lot simpler and there's no more `.h` files. Instead, any file you pass to `-i` will just get passed along to the C++ compiler unless it's `.ldpl` or `.lsc`. 

Meaning instead of this:

```
c++ -c gild.cpp -std=gnu++11 -o gild.o
ar -cvq gild.a gild.o
ldpl -i=gild.h gild.ldpl
```

Since there's no `.h` files required **and** you can pass `.o` files directly to `ldpl`, you can skip the `.a` archive and just do:

```
c++ -c gild.cpp -std=gnu++11 -o gild.o
ldpl -i=gild.o gild.ldpl
```

Or, better yet, for this simple extension I can just pass my c++ source code directly to LDPL and it'll compile along with everything else:

```bash
ldpl -i=gild.cpp gild.ldpl
```

As for syntax:

1. **DATA**: I didn't add new variable syntax, but I did make it a requirement that you must always declare variables in LDPL.  C++ extensions can access any LDPL variables by just using `extern string VAR_NAME`.
2. **SUBPROCEDURES**: I added `CALL EXTERNAL x`. So in GILD I have this now:

```
# run loop
call external gopher-init
while 1 is greater than 0 do
    call external gopher-get
    call sub-procedure gopher-print
    call sub-procedure gopher-prompt
repeat
```

I like how it's explicit! Before you couldn't tell which sub-procedures came from where.

Here's the LDPLNOISE change which shows the effect of updating to this new style on an extension: https://github.com/dvkt/ldplnoise/commit/59fd6d590369fd22f999b6d8c777c750c925d224

And the GILD one: https://github.com/dvkt/gild/commit/51c0d200ab10f76906044add0f29f1cc30240078

The next step is providing some sort of `ldpl.h` to make accessing LDPL variables and function names from C++ not so error prone.

I'm going to try to find a way to do it at compile time, so `ldpl_var("rl-input")` gets turned into a literal `VAR_RLr_UINPUT` in the extenion's source. I'll update this PR if I make any progress.

**Comment by dvkt** [comment]
Hi, me again with another update. I think it's in OK shape now. The C++ side is a bit more sane, so I think people could write some real extensions with it.

For the TLDR, here's the GILD patch for the latest: https://github.com/dvkt/gild/commit/a51b0de6167190f2f4db9c7ade4b560782333168

And the LDPLNOISE one: https://github.com/dvkt/ldplnoise/commit/dff8736f2ea02743f982f3703055f591483a7eb4

As you can see, the C++ is a lot simpler, the variable/function names are cleaner, and the `EXTERNAL` syntax makes everything more explicit.

So here's how it works now:

- Declare external variables you want to use in LDPL using `v IS EXTERNAL t` in the **DATA:** section. (Yes I added this after saying I didn't.)
- Call external sub-procedures in LDPL using `CALL EXTERNAL x` in the **PROCEDURE:** section.
- Define sub-procedures in C++ using `CAPS_AND_UNDERSCORES()` convention. 
- Initialize string and double variables in C++ using the same `CAPS_AND_UNDERSCORES`. 
- Pass `.a` static archives, `.o` object files, or even `.cpp` source code directly to the `ldpl` compiler to have it include the extension.

The key in this proposal is that external calls and variables have different name mangling rules than normal LDPL sub-procedures and variables, since they are read by humans. Only A-Z, 0-9, and `_` are valid, and all other characters get transformed into a `_`. 

I initially tried getting something like this working:

```c++

void window_draw()
{
     for(size_t i = 1;i <= LDPL_NUM(window.rows);i++)
     {
          LDPL_NUM(window.row, i);
          LDPL_CALL(window.draw-row);
     }
}
```

But it seems impossible to change the case of identifiers with C macros, and I'm no C++ template wizard.

Another idea was to have the compiler store all `external` LDPL variables as vectors or maps, then you could do `ldpl_num("window.rows")` and it would look up the proper variable for you, but I really like how plain the C++ is that LDPL spits out. The variables are just variables, y'know? Getting fancy and storing variables in a map that you can only access with functions kinda seems to defeat the purpose. (Also, I bet it would be slower, but I'm a terrible gambler.)

So, instead, I think it makes sense to say, "Hey, if you're writing an LDPL extension, here are the rules for naming your variables and functions:

1. They must be in ALL CAPS.
2. The only characters allowed are `A-Z`, `0-9`, and `_`.
3. **All** other characters on the LDPL side are converted to `_`.

For example:

- `window.rows IS external text` => `string WINDOW_ROWS;`
- `const.first-atom IS external number` => `ldpl_number CONST_FIRST_ATOM;`
- `CALL EXTERNAL sdl/update-loop` => `SDL_UPDATE_LOOP();` 

Then we don't need a `register` hook or translation layer between LDPL and C++. The biggest "surprise" with this approach is that `window.rows` and `WINDOW/rows` will both mangle to `WINDOW_ROWS`. But the advantage is the simplicity, and you don't have to `extern` anything since you're defining it all. 

(Please note that my original original approach was to just `#define GOPHER_GET SUBPR_GOPHERr_UGET`, so I'm already used to `CAP_NAMES()` in the C++ and I may be a bit biased!)

Anyway let me know what you think! We can also explore the `LDPL_VAR("window.rows")` route or any other angle if you want to go that direction too.

**Comment by Lartu** [comment]
> Should it be CALL EXT-PROCEDURE foo

You can call it whatever you like. Choose the one you prefer, either one is fine with me.

> For the TLDR, here's the GILD patch for the latest: dvkt/gild@a51b0de
And the LDPLNOISE one: dvkt/ldplnoise@dff8736

Hey, really nice looking!

> Pass .a static archives, .o object files, or even .cpp source code directly to the ldpl compiler to have it include the extension.

So you don't have to do anything else to your .cpp files? Just code and include them? No LDPL `.h` files nor anything?

> The key in this proposal is that external calls and variables have different name mangling rules than normal LDPL sub-procedures and variables, since they are read by humans. Only A-Z, 0-9, and _ are valid, and all other characters get transformed into a _.

This is awesome! Ahaha! Great idea!

I love the route you've taken with this! I love it and would definitely use it and add it to LDPL, I just love it. There's just one thing I didn't really understand: you declare `EXTERNAL` variables *from* LDPL so you can use them from both C++ and LDPL, right? All other LDPL variables are not supposed to be accessed from C++, right?

**Comment by dvkt** [comment]
> You can call it whatever you like. Choose the one you prefer, either one is fine with me.

Okay, I do like `CALL EXTERNAL`because it's explicit and matches the variable version. Let's stick with that :+1: 

> So you don't have to do anything else to your .cpp files? Just code and include them? No LDPL .h files nor anything?

Correct! It's super simple:

```
$ cat simple.cpp 
#include <iostream>
void SIMPLE(){
        std::cout << "Very simple!" << std::endl;
}
$ cat simple.ldpl 
PROCEDURE:
CALL EXTERNAL simple
$ ldpl -i=simple.cpp simple.ldpl
LDPL: Compiling...
* File(s) compiled successfully.
* Saved as simple-bin
$ ./simple-bin
Very simple!
```

> I love the route you've taken with this! I love it and would definitely use it and add it to LDPL, I just love it. 

Awesome! I hope people use it to build some weird stuff. Do you think I should add a short section to the README, or what would be the best next step to get it included in an official release? 

> There's just one thing I didn't really understand: you declare EXTERNAL variables from LDPL so you can use them from both C++ and LDPL, right? All other LDPL variables are not supposed to be accessed from C++, right?

That's right! Do you want all variables available to C++ by default? The idea with this approach is that the C++ extension can create a bunch of variables and your LDPL program opts-in to which ones it wants to use.

```
$ cat var.cpp
double A, B, C;
double SUM;
void ADD(){
        SUM = A + B + C;
}
$ cat var.ldpl 
DATA:
a IS external number
b IS external number
sum IS external number
PROCEDURE:
DISPLAY "number 1: " 
ACCEPT a
DISPLAY "number 2: " 
ACCEPT b
CALL EXTERNAL add
DISPLAY "sum: " sum CRLF
```

Output:
```
number 1: 10
number 2: 20
sum: 30
```

So even though the C++ uses the `C` variable, we didn't have to use it in our LDPL.

**Comment by Lartu** [comment]
I like what you did, I wouldn't change a thing. In the future if we see something needs some fine tuning, we'll take care of it, but there's no point on predicting and fixing without any actual feedback, so for me this is more than fine (and I don't really think we'll have to change anything anyway).

> Awesome! I hope people use it to build some weird stuff. Do you think I should add a short section to the README, or what would be the best next step to get it included in an official release?

Well, this is without a doubt what will take LDPL from 2.3.0 to 3.0.0, this is no minor update! So, in order to have everything ready for release, I'd love if you could document how to use this new extension in the LDPL reference. If you'd like to modify the README and say something like "you can even interface LDPL with C++!" that would also be awesome. Aside from that, I'm merging, so nothing left to do!

Thank you thank you thank you for this extremely wonderful contribution!

**Comment by Lartu** [comment]
You've made SDL work with LDPL. This is incredible. I'm at a loss for words. I can't believe this, haha!

**Comment by dvkt** [comment]
> I like what you did, I wouldn't change a thing. In the future if we see something needs some fine tuning, we'll take care of it, but there's no point on predicting and fixing without any actual feedback, so for me this is more than fine (and I don't really think we'll have to change anything anyway).

Great! Sounds good!

> So, in order to have everything ready for release, I'd love if you could document how to use this new extension in the LDPL reference. If you'd like to modify the README and say something like "you can even interface LDPL with C++!" that would also be awesome. Aside from that, I'm merging, so nothing left to do!

Wonderful! I'll get to work on updating the README and LDPL reference. I was able to log into Gitbook so I'll send the requests there.

> You've made SDL work with LDPL. This is incredible. I'm at a loss for words. I can't believe this, haha!

🤓

**Comment by Lartu** [comment]
Great! 😄

**Comment by dvkt** [comment]
Just added an "Extensions" section to the GitBook:

https://ldpl.gitbook.io/reference/extensions/c++-extensions

I'll add more soon.

**Comment by Lartu** [comment]
Great! What more will you add? Do you want me to document the `GOTO` function or you'd like to do it yourself?

**Comment by dvkt** [comment]
I just saw your `GOTO` docs, lol! They are great!

**Comment by Lartu** [comment]
Thank you! That was fast, I have JUST published them! :laughing:

**Pull request merged**
