### PR TITLE
Import statement

### PR DESCRIPTION
**Pull request by fireasembler**
added an import statement of the following form:
`IMPORT <string>`
you can only import before any other segment is declared.

### CODE REVIEW

**Comment by dgarroDC** [comment]
This is great! I changed so the path is relative to the file where you use `IMPORT` instead of your working directory.

**Comment by fireasembler** [comment]
didn't realize that it didn't work like that already. that's a fail on my part 😅.
thank you for fixing it!

**Comment by Lartu** [comment]
This is wonderful, thank you very much! This feature was something we were missing since LDPL was released, so I'm really grateful for this!

There's only one thing (not your fault though, it's the way LDPL works at the moment) that should be fixed. If I declare two files, `source.ldpl` and `included.ldpl` like this:

source.ldpl:
```
import "included.ldpl"
data:
  foo is number
procedure:
  display foo```

included.ldpl
```
procedure:
  store 100 in foo```

When I try to compile source.ldpl it raises `LDPL Error: Malformed statement  (included.ldpl:2)` because when included.ldpl is compiled the variable foo doesn't exist yet. I think should be fixed in some way that allows included files to use variables from files included later. What do you think? Is there any quickfix may have seen when working on this that may fix this? Maybe no fix is needed?

**Comment by dgarroDC** [comment]
I prefer the current behavior, having a dependency DAG with no circular dependencies.

**Comment by fireasembler** [comment]
yeah, this isn't a bug - it's a feature.
in almost all languages, a file you import into your current file is a file you rely on, and not the other way around. it would make no sense for the file you imported to rely on your variables.

**Comment by dgarroDC** [comment]
I think this should be allowed:

source.ldpl:
```
import "libA.ldpl"
import "libB.ldpl"
```

libA.ldpl:
```
import "libC.ldpl"
```
libC.ldpl:
```
DATA:
libC.var is number
```

Currently, when you compile `source.ldpl` you get `LDPL Error: Duplicate declaration for variable LIBC.VAR (libC.ldpl:2)`. One way to solve it is ignoring files we already compiled. The problem with this is that its main code will only be ran once, but is that really a problem?

**Comment by fireasembler** [comment]
I don't think it's a big problem

**Comment by Lartu** [comment]
We could add a warning telling that a variable has been redeclared, but not fail if a variable already exists. This is very easy to implement and would fix everything!I agree with what @dgarrodc said about DAGs.

**Comment by Lartu** [comment]
Thinking about this a little better, this could bring a lot of problems and a lot of checks would be required, that might end up being a little counter-intuitive. I'd rather keep things the way they are right now (with `IMPORT` working the way @fireasembler made it).

Once more, thank you very much @fireasembler for your wonderful contribution!

**Pull request merged**
