### PR TITLE
LDPL 4.5 LTS

### PR DESCRIPTION
**Pull request by Lartu**
This repository has been left rather unattended for some time now. I want that to change. @xvxx has suggested "finishing" the language, so to speak, and leaving it in a usable state that can be updated over time to ensure it still works. I call this LDPL LTS.

LDPL was partly abandoned because I attempted to add multithreading extensions to it, and the code was a mess, and they couldn't be trusted. Then COVID came along, and I did have a hard time working on the project.

This pull request fixes all of that. I've cleaned up the repo, removed the multiprocessing extensions, and rolled everything back to before the meteorite hit LDPL.

I don't want to do a tagged release yet, though. I will field-test LDPL via the [Advent of Code](https://adventofcode.com/) starting tomorrow. And if things work the way they are supposed to, LDPL 4.5 Groovy Gualicho should, at long last, see the light of day.

### CODE REVIEW

**Comment by Lartu** [comment]
@xvxx, @dgarroDC I'd love to know what you think about this.

**Comment by Lartu** [comment]
I'm merging this because, in any case, the codebase in main is broken. This should, ideally, fix it. And if it doesn't it's at the very least less broken than that one.

**Comment by xvxx** [comment]
I love this idea! There is a fair bit of LDPL code out there, it would be great if it kept working in perpetuity.

I personally don't feel that the language needs to evolve too much, especially since it supports extensions, so I love the idea of an "LTS" mode. I certainly have kept checking in every few months/years, and would love to continue doing so in the future.

**Comment by Lartu** [comment]
Wonderful! We agree that if it evolves _too_ much, it will turn into a chicken with a tie. Nobody wants that. LTS and only adding features if they are absolutely necessary sounds wonderful too.

**Pull request merged**
