### PR TITLE
Improve block closing errors

### PR DESCRIPTION
**Pull request by dgarroDC**
Now we check proper closing of nested blocks, throwing error if we find something like this:
```ldpl
PROCEDURE:

sub-procedure mySubprocedure
    if "" is equal to "" then
        while "" is not equal to "" do
end sub-procedure
    end if
        repeat
```

We also check that there isn't an unterminated procedure block, like this:
```ldpl
PROCEDURE:

sub-procedure mySubprocedure
```

### CODE REVIEW

**Comment by Lartu** [comment]
Hello there! Has this been tested with nested ifs and nested loops and all of that? If so, I'll merge ASAP! :smile: Thank you very much!

**Comment by dgarroDC** [comment]
Yes, it's working fine! But I just found out that you could declare a sub-procedure inside while/if blocks, and I guess that's not intended, right? I can change it before merge if that is the case, but maybe it should be stated in the referenced.

**Comment by Lartu** [comment]
No, you are right, that's not intended (in fact that should crash when trying to compile the C++ result). Great, thank you! I'll be merging now.

**Comment by Lartu** [comment]
Thank you very much for your contribution! :confetti_ball:

**Comment by dgarroDC** [comment]
You're welcome! 

> in fact that should crash when trying to compile the C++ result

I think that it actually compiles fine. For example:

```ld
PROCEDURE:
while 0 is equal to 0 do
    sub-procedure mySubprocedure
        return
    end sub-procedure
repeat
``` 
Produces this valid C++ code:

```C++
...
ldpl_number VAR_ARGC;
ldpl_number VAR_FILEc45_LOADED;
ldpl_vector<string> VAR_ARGV;
void SUBPR_MYSUBPROCEDURE(){
return;
}
int main(int argc, char *argv[]){
cout.precision(numeric_limits<ldpl_number>::digits10);
srand (time(NULL));
for(int i = 1; i < argc; ++i)
VAR_ARGV[i-1] = argv[i];
VAR_ARGC = argc - 1;
while (num_equal(0, 0)){
}
return 0; 
}
```

But yeah, it doen't make any sense, I'll change it next.

**Comment by Lartu** [comment]
Awesome!

**Pull request merged**
