### PR TITLE
STORE LENGTH OF vector

### PR DESCRIPTION
**Pull request by dvkt**
In action:

```
DATA:
count IS NUMBER
names IS TEXT VECTOR
ages IS NUMBER VECTOR

PROCEDURE:
STORE 81 IN ages:0
STORE 75 IN ages:1
STORE 102 IN ages:2

STORE "Marilyn" IN names:0
STORE "Dillsworth" IN names:1
STORE "Rogert" IN names:2
STORE "Pepperberry" IN names:3

STORE LENGTH OF ages IN count
DISPLAY count " ages" 
DISPLAY " & " 
STORE LENGTH OF names IN count
DISPLAY count " names" CRLF

### CODE REVIEW

**Comment by Lartu** [comment]
Woah, neat! Thank you very much for your contribution! Much appreciated!

**Comment by Lartu** [comment]
Hello! We've found a problem with STORE LENGTH OF. The thing is, when you look at a vector position and the value has not been initialized, it is initialized implicitly so the length of the vector grows by one. This, obviously, is very counter-intuitive and the solution to that issue is something that escapes this compiler, so I have two possible solutions:

One would be "COUNT INITIALIZED POSITIONS OF", that's just a rename of this funcion.

I'd rather just remove it for now. It's quite counter-intuitive and that goes against the philosophy of the language 😔

I'm sorry for not having realized this before.

**Comment by dvkt** [comment]
Ahh whoops! I didn't realize that. 

Is your plan to keep that behavior for vectors?  Because I'd think you could change the `[]` operators to return a default value if the key doesn't exist in the vector, if you wanted.

**Comment by Lartu** [comment]
I can look into that, but I believe it's not that easy for you cannot forsee on which side of the assignment operator the map will be.

**Comment by dvkt** [comment]
I see! I have been poking around and see what you mean, right now it's nice how flexible `get_c_variable` is in the compiler. You'd maybe have to check for the vector type and do an insert/push or something special in all the STORE code. 

I am :+1: on removing this until there's a less confusing solution :+1:

**Comment by Lartu** [comment]
Great, thank you! I'll check the code later and see what I can do, but checking the length of an LDPL VECTOR was not something I ever had in mind. Given that they aren't lineal, a size parameter may not be as expressive or useful as in other languages. Awk took the same decision. I'd rather keep and update a myvector.length variable, separately.

Thank you very much!

**Comment by dvkt** [comment]
:+1: makes sense, I like this way of thinking, yes! I was originally reaching for `STORE LENGTH OF vector` to iterate over a list (and because the syntax was no addition) but I can track all that separately.

**Comment by Lartu** [comment]
Yay! That's the idea. In AWK you can't get the length of a vector and you end up using tracking variables. It's not the most comfortable thing in the world, but I find it to be consistent with the data structures used.

**Pull request merged**
